### ISSUE TITLE
Facebook switching to Oauth 2.0

### ISSUE THREAD

**Issue by jonathanstegall** [pengkong/A3M-for-CodeIgniter-2.0#1]
I got an urgent notice from Facebook, indicating that my app will need to switch to Oauth 2.0 for security. I'm assuming, then, that a3m is using the old Oauth method.

Apparently, all apps and sites are required to update to Oauth 2.0 by September 1, 2011. In the meantime, we are expected to either upgrade or switch to an interstitial page that removes authentication data, ASAP.

Seems like it would be a great time to update the library.

**Comment by pengkong** [comment]
Hi Jon,

I got the same notice too.
Im not so sure why im getting it cuz A3M2.0 is already using oauth.
Will have to look into it when i have time. If you do it kindly share your
solution with me please.

Thank you!

On Thu, May 19, 2011 at 11:30 AM, jonathanstegall <
reply@reply.github.com>wrote:

> I got an urgent notice from Facebook, indicating that my app will need to
> switch to Oauth 2.0 for security. I'm assuming, then, that a3m is using the
> old Oauth method.
> 
> Apparently, all apps and sites are required to update to Oauth 2.0 by
> September 1, 2011. In the meantime, we are expected to either upgrade or
> switch to an interstitial page that removes authentication data, ASAP.
> 
> Seems like it would be a great time to update the library.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pengkong/A3M-for-CodeIgniter-2.0/issues/1

## 

Best Regards,
PK

**Comment by BeSublime** [comment]
Has anyone had the chance to take a look at this yet? I'm having issues with facebook signup/in on A3M and am wondering if this is related.

**Comment by OctavioFuenzalida** [comment]
https://github.com/brennannovak/codeigniter-facebook-oauth

oauth 2.0

**Comment by donjakobo** [comment]
I'm still running a3m for my apps, and no problem with Facebook

**Comment by steventen** [comment]
Hope this module can keep updating, really useful module for me

**Comment by donjakobo** [comment]
@steventen , are you having issues with the fb module?

**Comment by steventen** [comment]
Hi, @donjakobo. Yes, when I try to sign up, the browser will display warnings like: "This webpage has a redirect loop....This webpage... has resulted in too many redirects" I dont know why?

**Comment by donjakobo** [comment]
@steventen, I checked and FB is working just fine.  IF you are getting redirect warnings it is BECAUSE you didn't configure 'allowed' domains for your FB application, it will otherwise FAIL to redirect/accept the login, but will still send you back to the root of your site (which might create a loop for you).

To test this, LOG OUT of fb, then try the fb login, you should see ANY errors at that point when the login comes up, I found this and it said "your requesting domain does not match application.. blah blah" once I updated it and added *.domain.com it worked just fine.

Again, no issues here.

**Comment by jamaluddinrumi** [comment]
is a3m worked with oauth2 as facebook using it ? ive never used a3m before. and i will try it now. hope it will works !
