### ISSUE TITLE
Google URL not correct?

### ISSUE THREAD

**Issue by masterdam79** [pengkong/A3M-for-CodeIgniter-2.0#11]
When clicking the "Sign in with your account from: Google" I'm not redirected to the Google login page.

Get the "400. That's an error.

The page you requested is invalid. That's all we know." page.

Great stuff, will keep testing, thanks!

**Comment by toffentoffen** [comment]
Hi, 

I get the same error have you solved.

**Comment by toffentoffen** [comment]
I had the same error, taht was caused because my config['base_url'] was not complete example http://mydomain.com/a3m/. I had /a3m/ and with this baseurl google can not redirect.

**Comment by donjakobo** [comment]
@morfeo8marc :+1:  so I will close this issue as it is a config requirement for `base_url`
