### ISSUE TITLE
MongoDB?

### ISSUE THREAD

**Issue by dovy** [pengkong/A3M-for-CodeIgniter-2.0#12]
Any plans to port this into Mongo as well?

**Comment by donjakobo** [comment]
No, currently none, but you are welcome to fork and offer an option **:)**
It would be more of a question whether CodeIgniter supports MongoDB IMHO. 

**Random sources for CI + MongoDB:**
- http://codeigniter.com/forums/viewthread/162420/
- http://stackoverflow.com/questions/2248789/mongodb-and-codeigniter
