### ISSUE TITLE
facebook_helper.php

### ISSUE THREAD

**Issue by SamoSlaus** [pengkong/A3M-for-CodeIgniter-2.0#18]
Well there's something wrong with facebook_helper.php . The code is double and after removig double code i traced error to this $metadata = $this->getMetadataCookie();

after renaming getMetadataCookie() to getMetadataCookieName() I get this error:

Message: array_key_exists() [function.array-key-exists]: The second argument should be either an array or an object

**Comment by donjakobo** [comment]
Good catch on the duplicate code @SamoSlaus .  I've cleaned up the code that was duped, do you have a fix for the error you presented (I haven't had the time to do a test of this yet).

**Comment by SamoSlaus** [comment]
Well indeed i have a fix. I commented this line of code $base_domain = $this->getBaseDomain();  and now its working like a charm.

**Comment by donjakobo** [comment]
@SamoSlaus, why is 'commenting' this out a solution tho? I haven't had this error before and I've used an (minus the duplication) identical `facebook_helper.php` file

**Comment by SamoSlaus** [comment]
Maybe you forgot to write a function called getMetadataCookie() or is this just a typo? Couse there is a function calledgetMetadataCookieName().

**Comment by donjakobo** [comment]
@SamoSlaus, `facebook_helper.php` is a direct copy from the Facebook SDK library, nothing was modified by hand (or should not have been, if it got snuck in there, which I highly doubt).
