### ISSUE TITLE
Fatal error: Call to undefined method Facebook

### ISSUE THREAD

**Issue by agusesetiyono** [pengkong/A3M-for-CodeIgniter-2.0#20]
i find this error. when i logged in using facebook its okay, but when access another controller that corresponding with facebook account i got error.
Fatal error: Call to undefined method Facebook::getMetadataCookie() in .../application/modules/account/helpers/facebook_helper.php on line 1167

please help me to resolve this error.

**Comment by donjakobo** [comment]
Closing as this has already been committed, my mistake...
