### ISSUE TITLE
Facebook profile picture error

### ISSUE THREAD

**Issue by sfjamrock** [pengkong/A3M-for-CodeIgniter-2.0#22]
I notice that if a user log on with their Facebook account their profile picture url is stored in my database but the system can't retrieve it correctly. plus the url seems to be wrong, in account/account_profile when the pic is not uploaded directly.

**Comment by donjakobo** [comment]
Why not help by making a fix and committing the code back?

**Comment by sfjamrock** [comment]
I did a work around for this issue, not my best work but it solves Facebook issue, I will submit it for review.

**Comment by donjakobo** [comment]
I've got a helper that I use for this issue, I am integrating it into my [A3M Bootstrapped edition](https://github.com/donjakobo/A3M)
