### ISSUE TITLE
Twitter registration issue

### ISSUE THREAD

**Issue by sfjamrock** [pengkong/A3M-for-CodeIgniter-2.0#23]
I get the  following error  when using the twitter functions (currently the registration function). I have configured the Config file correctly so I don't think that's the issue.

Fatal error: Uncaught exception 'EpiOAuthException' in /home/content/08/10188508/html/application/modules/account/helpers/jmathai-twitter-async/EpiOAuth.php:423 Stack trace: #0 /home/content/08/10188508/html/application/modules/account/helpers/jmathai-twitter-async/EpiOAuth.php(393): EpiOAuthException::raise(Object(EpiCurlManager), false) #1 /home/content/08/10188508/html/application/modules/account/helpers/jmathai-twitter-async/EpiOAuth.php(45): EpiOAuthResponse->__get('oauth_token') #2 /home/content/08/10188508/html/application/modules/account/controllers/connect_twitter.php(95): EpiOAuth->getAuthenticateUrl() #3 [internal function]: Connect_twitter->index() #4 /home/content/08/10188508/html/system/core/CodeIgniter.php(359): call_user_func_array(Array, Array) #5 /home/content/08/10188508/html/index.php(202): require_once('/home/content/0...') #6 {main} thrown in /home/content/08/10188508/html/application/modules/account/helpers/jmathai-twitter-async/EpiOAuth.php on line 423

**Comment by donjakobo** [comment]
This sounds/looks like a `curl` issue. Haven't seen this issue before, but looks like it from this:
`/home/content/08/10188508/html/application/modules/account/helpers/jmathai-twitter-async/EpiOAuth.php(393): EpiOAuthException::raise(Object(EpiCurlManager), false)`

**Comment by sfjamrock** [comment]
@donjakobo  and @pengkong, I was trying to debug this issue (I really getting tired of it) and I notice that account / helpers / jmathai-twitter-async has not been updated for over 2 years but Twitter API had a major updated out now for about 4 months now. I think this could be the reason why Twitter as been causing me issues. I will be looking into ways to   fix this issue but I would like as much help as possible to updating the code.

**Comment by donjakobo** [comment]
@sfjamrock, I'm running an out of the box a3m / twitter setup, and have had no issues.  I have users connecting with twitter, and the last thing I had issue with was Facebook as they retired an older connection method that needed a fresh code update from them.

**Comment by sfjamrock** [comment]
@donjakobo here is a link to my site where I'm experiencing the issue http://www.teleworkportfolio.com/account/sign_up I don't know where the issue is popping up from and I can't out rule the update as a potential issue, since my twitter developer profile was set up after then update was made live. any help in debug this issue would be appreciate it

**Comment by donjakobo** [comment]
@sfjamrock I think your issue is outlined in the **note:**  https://github.com/donjakobo/A3M/blob/master/README.md#note

Check out my updated A3M (its not stable yet, but worth a look)
