### ISSUE TITLE
Find new error hen signin/up with facebook

### ISSUE THREAD

**Issue by agusesetiyono** [pengkong/A3M-for-CodeIgniter-2.0#25]
A PHP Error was encountered

Severity: Notice

Message: Use of undefined constant CURLOPT_IPRESOLVE - assumed 'CURLOPT_IPRESOLVE'

Filename: helpers/facebook_helper.php

Line Number: 960

how to resolve this...??

**Comment by donjakobo** [comment]
Looks like you don't have cURL enabled, follow this guide for more detail:
http://www.tomjepson.co.uk/enabling-curl-in-php-php-ini-wamp-xamp-ubuntu/

**Comment by agusesetiyono** [comment]
my web application is okay before this, but suddenly got this error...
my app is here http://learning.asiknya.org

if curl is disable  how to enable it? i found on the article you give is in localserver only, isn't right?

**Comment by donjakobo** [comment]
@agusesetiyono you need to find out why cURL is disabled by yourself, that is outside of the scope of this application.  The link I supplied was for reference only, you need to google the error to find the solution. Sorry.
