### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by dovy** [pengkong/A3M-for-CodeIgniter-2.0#26]
@donjakobo , you said a new version was coming with integrated Bootstrap, etc? When is that going to be released? I'd love to start adapting it. Thanks.

**Comment by donjakobo** [comment]
@dovy, I'm almost done it all, I'ts been a hectic busy last few weeks for me, between starting a new job late last year, and running around through the holidays, I was able to do a good portion of it.

Excuses aside, the code is sitting almost done, finishing some documentation, and some bug fixes.  I was planning on integrating Microsoft LIVE (/hotmail) oauth into it as well, but I might release it soon without it, and do that as a next milestone.

The way it currently looks is, I gutted out all the old CSS / grid, replaced it with Twitter's bootstrap + gutted the whole `/module/` approach with which @pengkong began (as I personally hate diving into that folder to change things, it pretty much fractures your application having to modify your user account details in a module container!).

Anyway, I will try to push it this weekend, so stay tuned. I might just push it as a beta right now with knowingly broken stuff.  I'll update here once I do so.

Thanks for checking in, and sorry about the delay, I've kindof inherited this from @pengkong ;)

**Comment by dovy** [comment]
I'll gladly assist with the bugs now. I still want to integrate Hybridauth and only use A3M as the account management section. Either way, excited to see your work. Thanks!

**Comment by dovy** [comment]
Better yet, just make a new brach and I'll help go to town.  ;)

**Comment by donjakobo** [comment]
@dovy, not to highjack _A3M_ but I need more control over the url / project settings, so I've updated my fork with my code: 

https://github.com/donjakobo/A3M

Feel free to grab it, and commit changes back, I know offhand that the `sign_up.php` view needs re-skinning, otherwise A LOT of it is done.  I need to update more documentation and review libraries (twitter / facebook / etc;) and update those details as well. Would appreciate a hand :)

**Comment by donjakobo** [comment]
I've commited many updates tonight _yawn_
Check them out, it should all ( _fingers crossed_ ) be working :+1:

**Comment by sfjamrock** [comment]
I want to add LinkedIn sigh up to the mix, I want to make a contribution to the group so I think adding that would open   up more opportunity. Also at some point it would be nice to be able to be DE-select login option without having to edit the database I think if I only want facebook as a login I want to be able to use this system just for that. So what do you guys think.

**Comment by donjakobo** [comment]
The 'deselection' method you speak of exists under 'linked accounts' please check out the new fork that I have (as I moved away from @pengkong 's build due to a different direction with the project).

I'm closing this for now as this is older code in this repo.
