### ISSUE TITLE
Unable to load the requested file: connect_create.php

### ISSUE THREAD

**Issue by chego77** [pengkong/A3M-for-CodeIgniter-2.0#27]
http://***/account/connect_create

**Comment by donjakobo** [comment]
I'll check into this, what page was this requested on? Also are you posting this for A3M bootstrapped? Or @pengkong 's older version here?

**Comment by donjakobo** [comment]
Closing as this shouldn't be an issue in this repo...

**Comment by chego77** [comment]
A3M bootstrapped
