### ISSUE TITLE
define('Auth_OpenID_RAND_SOURCE', null);

### ISSUE THREAD

**Issue by chego77** [pengkong/A3M-for-CodeIgniter-2.0#28]
CryptUtil Line 23
When I chang to null
can not Auth google and yahoo
google error message:invalid_request
Yahoo error message:
Sorry! There is an error with the request we received from the website you are trying to use. Please try again in a few minutes. If this error persists please contact the site administrator.

**Comment by donjakobo** [comment]
please check the new repo at: 
https://github.com/donjakobo/A3M
