### ISSUE TITLE
Twitter login expire after browser close

### ISSUE THREAD

**Issue by viperfx** [pengkong/A3M-for-CodeIgniter-2.0#3]
Hi, 

When using firefox, I can close the browser and re-open it and it will still remember me as a user. However when I use chrome, after the restart of browser, it asks me to sign in again. I have tested with 2 other people, and they say the same thing.

What is the issue here? How can I allow the user to be signed in until they sign out?

Thank you.

**Comment by pengkong** [comment]
play around with your config.php

the part on sessions.

make it die on browser close in the ci config.php file.

On Sun, Nov 27, 2011 at 12:46 AM, viperfx <
reply@reply.github.com

> wrote:
> 
> Hi,
> 
> When using firefox, I can close the browser and re-open it and it will
> still remember me as a user. However when I use chrome, after the restart
> of browser, it asks me to sign in again. I have tested with 2 other people,
> and they say the same thing.
> 
> What is the issue here? How can I allow the user to be signed in until
> they sign out?
> 
> Thank you.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pengkong/A3M-for-CodeIgniter-2.0/issues/3

## 

Best Regards,
PK

**Comment by pengkong** [comment]
```
        If you are unable to view the images in this email, please click here.
        To ensure delivery to your inbox, please add victoria@vanitytrove.com to your Address Book





                     

                                Hi! I would like to share this amazing site called VanityTrove with you, where you will receive a personalized box of Beauty samples delivered right to your doorstep at just $25 monthly! Join now and get exclusive products and offers!
                                xoxo,
                                Peng Kong
                                Join the club!
                                Get your monthly subscription on VanityTrove to receive your box
                                of deluxe beauty samples delivered right to your doorstep.
                                You will love it!
                         



 
Connect with us! 

    Copyright © 2011, VanityTrove. All Rights Reserved.
```
