### ISSUE TITLE
reCaptcha not showing

### ISSUE THREAD

**Issue by wwwdotphilip** [pengkong/A3M-for-CodeIgniter-2.0#30]
I enabled the $config['sign_up_recaptcha_enabled'] = TRUE;
set my public and private key but when I go to the signup page no reCaptcha appeared. I follow the tutorial from http://joshualholmes.wordpress.com/2011/02/27/a3m-peanutbutter-%E2%80%93-for-codeigniter-2-0-recaptcha/

**Comment by donjakobo** [comment]
please check the new repo at: 
https://github.com/donjakobo/A3M
