### ISSUE TITLE
Twitter "Cancel, and return to app"

### ISSUE THREAD

**Issue by markstreich** [pengkong/A3M-for-CodeIgniter-2.0#9]
When linking or registering a twitter account, if a user clicks "Cancel, and return to app" it will return you to the callback URL with a "denied" parameter. 

controllers/connect_twitter.php doesn't check for "denied", so it sends the user back to twitter again.

I fixed this by adding at line 26:

``` php
        if ($this->input->get('denied'))
        {
      $this->authentication->is_signed_in() ?
        redirect('account/account_linked') :
          redirect('account/sign_up');
    }
```

**Comment by donjakobo** [comment]
@gllen feel free to fork, and request a merge on all these bug fixes. I haven't had the time to do a test of the virgin setup, as I've only recently re-updated A3M to the latest CI version.

Appreciate the hard work!

**Comment by markstreich** [comment]
I'd love to help but in addition to being a CI newb I'm also a complete git newb :)

I get really confused about how I would test on a "virgin setup", but with my own configuration files (API keys etc), but make sure those files don't become public when I request a merge.

I'm sure it's not that complicated, and that sounds really dumb, but I'm still learning.

**Comment by donjakobo** [comment]
@gllen, basically there is a button [fork] for this project, by 'forking' you make a copy for yourself of the project, you can then use the Windows client or Mac client (whatever your preference) to checkout code, and then re-commit it to your repository. At that point you would make a [pull request] to commit back to the 'master' (ie: this code repository).  Its a little complicated at first, but not at all hard.  

This method allows you to make changes, and 'suggest' them back to us.  A 'fork' also means branching or splitting from the main 'code tree' so to speak.

What I've done in some cases is gone through A3M forks and grabbed out bug fixes that others have created (but sometimes not commited as a pull request for this master branch)

**Comment by markstreich** [comment]
Thank you very much for taking the time. It's something I've been wanting to better understand (git), but it's still hazy how everything fits together. I'll try though :)

**Comment by donjakobo** [comment]
@gllen, I've taken your code fixes and picked out the ones that work and commited them to the master. Thanks for the input! Keep it up :+1:
